#!/bin/bash
# ex: set filetype=sh expandtab shiftwidth=4

retval=0

error()
{
    printf -- "- $*\n" >&2
    retval=1
}

comment_pat='^#'
reference_pat='^\[[[:digit:]]\]'
subject_bad_start_pat='^[[:lower:]]'
subject_bad_end_pat='[[:punct:]]$'

line_num=0
while IFS= read -r line || [[ -n "$line" ]]; do
    [[ $line =~ $comment_pat ]] && continue
    [[ $line =~ $reference_pat ]] && continue

    line_num=$((line_num+1))
    length=${#line}
    if [[ $line_num -eq 1 ]]; then
        [[ $length -gt 50 ]] &&
            error "subject line exceeds 50 characters"

        [[ $line =~ $subject_bad_start_pat ]] &&
            error "subject line not capitalised"

        [[ $line =~ $subject_bad_end_pat ]] &&
            error "subject line terminated by punctuation"

    elif [[ $line_num -eq 2 ]]; then
        [[ $length -ne 0 ]] &&
            error "subject line followed by non-empty line"

    else
        [[ $length -gt 72 ]] &&
            error "line $line_num exceeds 72 characters"
    fi
done < "$1"

exit $retval
