#!/bin/bash
# ex: set filetype=sh expandtab shiftwidth=4

#retval=0
file="$1"

error()
{
    printf -- "- $*\n" >&2
}

comment_pat='^#'
reference_pat='^\[[[:digit:]]\]'
subject_bad_start_pat='^[[:lower:]]'
subject_bad_end_pat='[[:punct:]]$'

main()
{

    local retval=0
    local line_num=0

while IFS= read -r line || [[ -n "$line" ]]; do
    [[ $line =~ $comment_pat ]] && continue
    [[ $line =~ $reference_pat ]] && continue

    line_num=$((line_num+1))
    length=${#line}
    if [[ $line_num -eq 1 ]]; then
        [[ $length -gt 50 ]] && {
            error "subject line exceeds 50 characters"
            retval=1
        }

        [[ $line =~ $subject_bad_start_pat ]] && {
            error "subject line not capitalised"
            retval=1
        }

        [[ $line =~ $subject_bad_end_pat ]] && {
            error "subject line terminated by punctuation"
            retval=1
        }

    elif [[ $line_num -eq 2 ]]; then
        [[ $length -ne 0 ]] && {
            error "subject line followed by non-empty line"
            retval=1
        }

    else
        [[ $length -gt 72 ]] && {
            error "line $line_num exceeds 72 characters"
            retval=1
        }
    fi

done < "$file"

    return $retval
}

while ! main; do
    $EDITOR </dev/tty $file >/dev/tty
done

#exit $retval
